LIBNAME SASTEST "/home/u63652680/my_sas_data";

/* 2-1. PROC SORT (순서대로 정렬하기) */
PROC SORT DATA = SASHELP.CLASS OUT = TEST;
BY AGE;
RUN;

PROC SORT DATA = TEST;
BY DESCENDING AGE;
RUN;

/* 2-2. PROC PRINT (테이블 보여주기) */
PROC PRINT DATA = SASHELP.CLASS;
RUN;

PROC PRINT DATA = SASHELP.CLASS;
VAR AGE NAME;
RUN;

PROC SORT DATA = SASHELP.CLASS OUT = TEST;
BY AGE;
RUN;
PROC PRINT DATA = TEST;
VAR AGE NAME;
BY AGE;
RUN;

/* 2-3. PROC CONTENTS (테이블 속성 보기) */
PROC CONTENTS DATA = SASHELP.CLASS;
RUN;

PROC CONTENTS DATA = WORK._ALL_;
RUN;

/* 2.4 PROC FREQ (빈도 조회) */
PROC FREQ DATA = SASHELP.CLASS;
TABLE AGE HEIGHT;
RUN;

PROC FREQ DATA = SASHELP.CLASS;
TABLE AGE*HEIGHT;
RUN;

PROC FREQ DATA = SASHELP.CLASS;
TABLE AGE SEX;
RUN;

PROC FREQ DATA = SASHELP.CLASS;
TABLE AGE*SEX;
RUN;

PROC FREQ DATA = SASHELP.CLASS;
TABLE SEX*AGE*HEIGHT;
RUN;