/*
 * Chapter 08: PROC SQL Basics
 * 목적: PROC SQL을 사용하여 데이터를 추출 및 가공하고, 조건문과 그룹 연산을 활용하는 기초 SQL 문법 학습
 * 출처: https://wikidocs.net/book/2678
 */
LIBNAME SASTEST "/home/u63652680/my_sas_data";

/* 8-01 SQL로 표 만들기(FROM명령어로 불러오기) */
PROC SQL;
SELECT NAME, AGE, HEIGHT
FROM SASHELP.CLASS
;
QUIT;

PROC SQL;
SELECT *
FROM SASHELP.CLASS
;
QUIT;

/* 8-02 SQL로 테이블 만들기(CREATE TABLE AS명령어 추가) */
/* DATA문에서 KEEP과 비슷한 동작, 보여 줄 COLUMN 설정 */
PROC SQL;
CREATE TABLE TEST AS
SELECT NAME, AGE, HEIGHT
FROM SASHELP.CLASS
;
QUIT;

/* 8-03 SQL로 사칙연산하기 */
PROC SQL;
CREATE TABLE TEST AS
SELECT NAME, SEX, AGE, HEIGHT, AGE+HEIGHT
FROM SASHELP.CLASS
;
QUIT;

PROC SQL;
CREATE TABLE TEST2 AS
SELECT NAME, SEX, AGE, HEIGHT, SUM(AGE), MEAN(AGE), MEDIAN(AGE), MIN(AGE), VAR(AGE), STD(AGE)
FROM SASHELP.CLASS
;
QUIT;

/* 8-04 SQL로 새 칼럼 이름 부여하기(AS) */
PROC SQL;
CREATE TABLE TEST AS
SELECT NAME, SEX AS MALE_FEMALE, AGE+HEIGHT AS SUM
FROM SASHELP.CLASS
;
QUIT;

PROC CONTENTS DATA = TEST;
RUN;

/* 8-05 SQL 명령어들 */
/* 
COMPRESS : 특정 문자와 공백을 제거
TRIN : 뒤의 공백을 제거
TRASLATE : 특정 문자를 다른 문자로 대체
LOWCASE : 문자를 소문자로 변경
UPCASE : 문자를 대문자로 변경
SUBSTR : 특정 위치의 문자를 추출
SCAN : 특정 문자를 기준으로 특정 순서의 문자를 추출
CATX : 문자들 사이에 원하는 구분기호 삽입
FIND : 특정 문자의 위치를 찾는다
LEFT : 문자를 왼쪽으로 정렬
RIGHT : 문자를 오른쪽으로 정렬
PUT : 숫자칼럼을 문자칼럼으로 변경
INPUT : 문자칼럼을 숫자칼럼으로 변경
*/

PROC SQL;
CREATE TABLE TEST AS
SELECT NAME, AGE, COMPRESS(NAME,'ce') AS COMPRESS, TRANSLATE(NAME,'AA','ce') AS TRANS
, TRANWRD(NAME, 'ce', 'AAAA') AS TRANWRD, SUBSTR(NAME,1,3) AS SUBSTR, CATX('-',NAME,AGE) AS CATX
, FIND(NAME,'ce') AS FIND, PUT(AGE,5.) AS PUT, INPUT(PUT(AGE,5.),5.) AS COM_PUT
FROM SASHELP.CLASS
;
QUIT;

/* 8-06 SQL로 특정 데이터 추출하기(WHERE) */
PROC SQL;
CREATE TABLE TEST AS
SELECT NAME, AGE, HEIGHT
FROM SASHELP.CLASS
WHERE AGE = 12
;
QUIT;

PROC SQL;
CREATE TABLE TEST AS
SELECT NAME, AGE, HEIGHT
FROM SASHELP.CLASS
WHERE AGE = 12 AND 59 <= HEIGHT <= 61
;
QUIT;

PROC SQL;
CREATE TABLE TEST AS
SELECT NAME, AGE, HEIGHT
FROM SASHELP.CLASS
WHERE NAME='John'
;
QUIT;

/* 8-07 SQL로 데이터 정렬하기(ORDER BY) */
PROC SQL;
CREATE TABLE TEST AS
SELECT *
FROM SASHELP.CLASS
ORDER BY AGE
;
QUIT;

PROC SQL;
CREATE TABLE TEST AS
SELECT *
FROM SASHELP.CLASS
ORDER BY AGE DESC
;
QUIT;

PROC SQL;
CREATE TABLE TEST AS
SELECT *
FROM SASHELP.CLASS
ORDER BY AGE, HEIGHT
;
QUIT;

PROC SQL;
CREATE TABLE TEST AS
SELECT *
FROM SASHELP.CLASS
ORDER BY AGE, HEIGHT DESC /* 나이는 오름차순, 키는 내림차순 정렬 */
;
QUIT;

/* 8-08 SQL로 조건문 만들기(CASE WHEN) */
/* DATA문에서 IF와 비슷한 작동 */
PROC SQL;
CREATE TABLE TEST AS
SELECT *,
CASE WHEN AGE=12 THEN '열두살'
WHEN AGE=13 THEN '열세살' END AS NEW_AGE
FROM SASHELP.CLASS
;
QUIT;

DATA TEST;
SET SASHELP.CLASS;
IF AGE=12 THEN NEW_AGE='열두살';
ELSE IF AGE=13 THEN NEW_AGE='열세살';
RUN;

PROC SQL;
CREATE TABLE TEST AS
SELECT *,
CASE WHEN AGE=12 THEN '열두살'
ELSE '나머지' END AS NEW_AGE
FROM SASHELP.CLASS
;
QUIT;

/* 8-09 SQL로 그룹별로 연산하기(GROUP BY) */
PROC SQL;
CREATE TABLE TEST AS
SELECT *, SUM(AGE) AS SUM_AGE
FROM SASHELP.CLASS
GROUP BY SEX
;
QUIT;

/* 8-10 SQL로 그룹별 특정 데이터 추출하기(HAVING) */
/* 
SQL문 내에서 WHERE과 비슷한 동작을 수행하지만, 
GROUP BY과 WHERE은 SAS 문법 규칙에 의해 같이 사용 할 경우 에러가 발생하게 된다.
따라서, GROUP BY를 사용할 경우 HAVING명령어를 사용해야 한다.
*/
/*
WHERE은 이미 만들어져있는 칼럼에 대해서 사용,
HAVING은 새로 만든 칼럼에 대해서 사용하게 된다. */
PROC SQL;
CREATE TABLE TEST AS
SELECT *, SUM(AGE) AS SUM_AGE
FROM SASHELP.CLASS
GROUP BY SEX
HAVING SUM_AGE>120
;
QUIT;

PROC SQL;
CREATE TABLE TEST AS
SELECT *, SUM(AGE) AS SUM_AGE
FROM SASHELP.CLASS
GROUP BY SEX
HAVING AGE>13 AND SUM_AGE>120
;
QUIT;

/* 8-11 SQL명령어 순서 */
/*
SQL에서는 반드시 아래와 같은 순서를 지켜서 입력해야 한다.
1. PROC SQL
2. CREATE TABLE
3. SELECT
4. FROM
5. WHERE
6. GROUP BY
7. HAVING
8. ORDER BY
*/

PROC SQL;
CREATE TABLE TEST AS
SELECT *, SUM(AGE) AS SUM_AGE
FROM SASHELP.CLASS
WHERE HEIGHT<65
GROUP BY SEX
HAVING SUM_AGE>90
ORDER BY NAME
;
QUIT;

/* 8-12 SQL로 테이블에 없는 칼럼 생성 후 연산(CALCULATED) */
/* CALCULATED : 새롭게 계산된 칼럼을 활용하라는 명령어 */
PROC SQL;
CREATE TABLE TEST_1 AS
SELECT *, AGE+1 AS AGE_1,
CASE WHEN CALCULATED AGE_1>15 THEN 'Y' ELSE 'N' END AS CHECK_1
FROM SASHELP.CLASS
;
QUIT;

PROC SQL;
CREATE TABLE TEST_2 AS
SELECT *, AGE+2 AS AGE_2
FROM SASHELP.CLASS
WHERE CALCULATED AGE_2>15
;
QUIT;

PROC SQL;
CREATE TABLE TEST_2 AS
SELECT *, AGE+2 AS AGE_2
FROM SASHELP.CLASS
HAVING AGE_2>15
;
QUIT;

PROC SQL;
CREATE TABLE TEST_2 AS
SELECT *, AGE+2 AS AGE_2
FROM SASHELP.CLASS
HAVING CALCULATED AGE_2>15
;
QUIT;